class App {

    constructor(examContainer, sidebarContainer) {
        // reference to the the exam container (HTML element)
        this.examContainer = examContainer;

        // init the exam manager and get the exam list
        this.examManager = new ExamManager();
        this.exams = this.examManager.exams;

        // init the filter functionality
        this.filters = new Filters(sidebarContainer, this.examManager);
        // 'this' should be the one in this class, not the target element
        this.onFilterSelected = this.onFilterSelected.bind(this);
        // listening for the event generated by filters
        document.addEventListener('filter-selected', this.onFilterSelected);

        // finally, show all the exams (default)
        this.showExams(this.exams);
    }

    /**
     * Custom event handler: receive and show the filtered exam list
     * @param {*} event 
     */
    onFilterSelected(event) {
        // empty the exam table
        if(this.examContainer.innerHTML !== '') {
            this.examContainer.innerHTML = '';
        }

        // show all the things!
        this.showExams(event.detail);
    }

    /**
     * Create the HTML table for showing the exams
     * @param {*} exams 
     */
    showExams(exams) {
        for(let exam of exams) {
            const tr = document.createElement('tr');

            const tdDate = document.createElement('td');
            tdDate.innerText = exam.date.format('DD/MM/YYYY');

            const tdName = document.createElement('td');
            tdName.innerText = exam.name;

            const tdCredits = document.createElement('td');
            tdCredits.innerText = exam.credits;

            const tdGrade = document.createElement('td');
            tdGrade.innerText = exam.grade;

            tr.appendChild(tdDate);
            tr.appendChild(tdName);
            tr.appendChild(tdCredits);
            tr.appendChild(tdGrade);
            this.examContainer.appendChild(tr);
        }
    }
}